[mongodb]
mongodb.vara88s.site

[catalogue]
catalogue.vara88s.site

[redis]
redis.vara88s.site

[user]
user.vara88s.site

[cart]
cart.vara88s.site

[frontend]
frontend.vara88s.site

[mysql]
mysql.vara88s.site

[shipping]
shipping.vara88s.site

[rabbitmq]
rabbitmq.vara88s.site

[payment]
payment.vara88s.site

[all vars]
ansible_user=ec2-user
ansible_password=DevOps321